from .base import *

DEBUG = True
ALLOWED_HOSTS = ALLOWED_HOSTS or ["localhost", "127.0.0.1"]
CORS_ALLOW_ALL_ORIGINS = not CORS_ALLOWED_ORIGINS
AUTO_APPROVE_IDENTITY_VERIFICATION = env.bool(
    "AUTO_APPROVE_IDENTITY_VERIFICATION",
    default=True,
)
