# Generated by Django 5.2.13 on 2026-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mutual Consent Agreement', max_length=180)),
                ('terms', models.TextField()),
                ('duration_hours', models.PositiveIntegerField(default=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGNATURES', 'Pending signatures'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING_SIGNATURES', max_length=30)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='consents/signatures/')),
                ('signature_text', models.CharField(blank=True, max_length=180)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('signed_at',),
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie_image', models.ImageField(upload_to='identity/selfies/')),
                ('government_id_image', models.ImageField(upload_to='identity/government_ids/')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving license'), ('NATIONAL_ID', 'National ID'), ('OTHER', 'Other')], max_length=30)),
                ('document_last_four', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('selfie_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
