# Generated by Django 5.2.13 on 2026-06-11 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentagreement',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentagreement',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentagreement',
            name='previous_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='consents.consentagreement'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='consents.consentagreement'),
        ),
        migrations.AddField(
            model_name='consentsignature',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='consents.consentagreement'),
        ),
        migrations.AddField(
            model_name='consentsignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='consentsignature',
            constraint=models.UniqueConstraint(fields=('agreement', 'signer'), name='unique_signature_per_agreement_signer'),
        ),
    ]
