# Generated by Django 5.2.13 on 2026-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentagreement',
            name='requested_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consentsignature',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='consentsignature',
            name='location_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consentsignature',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='consentsignature',
            name='verification_status',
            field=models.CharField(default='VERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='device_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='facial_verification_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='location_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='identityverification',
            name='security_checks_passed',
            field=models.BooleanField(default=False),
        ),
    ]
